# Generated by Django 5.2 on 2025-04-18 06:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Savol matni')),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('CD', 'Coding')], help_text='Savol turi', max_length=2)),
                ('points', models.PositiveIntegerField(default=1, help_text='Savol uchun ball')),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Savol uchun vaqt chegarasi (sekundlarda)')),
                ('explanation', models.TextField(blank=True, help_text='To‘g‘ri javobning izohi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Quiz nomi, masalan, 'Matematika Test #1'", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Quiz ta'rifi", null=True)),
                ('difficulty', models.CharField(choices=[('oson', 'Oson'), ('orta', 'O‘rta'), ('qiyin', 'Qiyin')], default='oson', help_text='Quizning qiyinlik darajasi', max_length=20)),
                ('cover_image', models.URLField(blank=True, help_text='Quiz uchun jozibali rasm URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, help_text='Quiz davomiyligi, masalan, 30 daqiqa', null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Quiz boshlanish vaqti', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Quiz faol yoki yo‘qligi')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maksimal urinishlar soni')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz’lar',
            },
        ),
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_correct', models.PositiveIntegerField(default=10, help_text='To‘g‘ri javob uchun ball')),
                ('streak_bonus', models.PositiveIntegerField(default=5, help_text='Ketma-ket to‘g‘ri javoblar uchun bonus ball')),
                ('max_streak', models.PositiveIntegerField(default=3, help_text='Maksimal streak chegarasi')),
                ('star_thresholds', models.JSONField(default=dict, help_text="Yulduzlar chegarasi, masalan, {'3': 80, '2': 60, '1': 0}")),
            ],
            options={
                'verbose_name': 'Musobaqa sozlamasi',
                'verbose_name_plural': 'Musobaqa sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Fanning nomi, masalan, 'Matematika'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Fanning qisqa ta'rifi", null=True)),
                ('slug', models.SlugField(help_text="URL uchun qulay ID, masalan, 'matematika'", max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Fanning ikonka belgisi, masalan, emoji 📐 yoki rasm URL', max_length=50)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nishon nomi, masalan, 'Matematika Ustasi'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Nishon ta'rifi", null=True)),
                ('icon', models.CharField(blank=True, help_text='Nishon ikonka belgisi, masalan, emoji 🏆', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, help_text='Nishonni olgan foydalanuvchilar', related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nishon',
                'verbose_name_plural': 'Nishonlar',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Javob varianti matni', max_length=200)),
                ('is_correct', models.BooleanField(default=False, help_text='Bu variant to‘g‘ri yoki yo‘qligi')),
                ('question', models.ForeignKey(help_text='Variant qaysi savolga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizz.question')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='Savol qaysi quiz’ga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizz.quiz'),
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Umumiy ball')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='To‘g‘ri javoblar soni')),
                ('wrong_answers', models.PositiveIntegerField(default=0, help_text='Xato javoblar soni')),
                ('streak', models.PositiveIntegerField(default=0, help_text='Ketma-ket to‘g‘ri javoblar soni')),
                ('stars', models.PositiveIntegerField(default=0, help_text='Yulduzlar (0-3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('is_completed', models.BooleanField(default=False, help_text='Quiz tugallangan yoki yo‘qligi')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Urinish raqami')),
                ('quiz', models.ForeignKey(help_text='Topshirilgan quiz', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizz.quiz')),
                ('user', models.ForeignKey(help_text='Quiz topshirgan foydalanuvchi', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz topshirigi',
                'verbose_name_plural': 'Quiz topshiriklari',
                'unique_together': {('user', 'quiz', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(help_text='Leaderboard qaysi quiz’ga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='quizz.quiz')),
                ('entries', models.ManyToManyField(blank=True, help_text='Eng yaxshi natijalar ro‘yxati', to='quizz.quizsubmission')),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboard’lar',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Qisqa javob yoki kod uchun matn', null=True)),
                ('is_correct', models.BooleanField(default=False, help_text='Javob to‘g‘ri yoki yo‘qligi')),
                ('score', models.PositiveIntegerField(default=0, help_text='Ushbu javob uchun ball')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('selected_choice', models.ForeignKey(blank=True, help_text='Ko‘p tanlovli savol uchun tanlangan variant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizz.choice')),
                ('question', models.ForeignKey(help_text='Javob berilgan savol', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizz.question')),
                ('submission', models.ForeignKey(help_text='Javob qaysi topshirikka tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizz.quizsubmission')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(help_text='Quiz qaysi fanga tegishli', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizz.subject'),
        ),
    ]
