# Generated by Django 5.2 on 2025-04-17 07:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Contest Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish Vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash Vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Masala Nomi')),
                ('description', models.TextField(verbose_name='Masala Tavsifi')),
                ('difficulty', models.IntegerField(choices=[(1, 'Oson'), (2, 'O‘rta'), (3, 'Qiyin')], default=1, verbose_name='Daraja')),
                ('time_limit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Vaqt Limiti (sekund)')),
                ('points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Ball')),
                ('input_example', models.TextField(blank=True, verbose_name='Kirish Misoli')),
                ('output_example', models.TextField(blank=True, verbose_name='Chiqish Misoli')),
                ('test_cases_input', models.TextField(blank=True, verbose_name='Test Case Kirishlari')),
                ('test_cases_output', models.TextField(blank=True, verbose_name='Test Case Chiqishlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contest.contest', verbose_name='Contest')),
            ],
            options={
                'verbose_name': 'Masala',
                'verbose_name_plural': 'Masalalar',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Yuborilgan Kod')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACCEPTED', 'Qabul Qilindi'), ('WRONG_ANSWER', 'Noto‘g‘ri Javob'), ('TIME_LIMIT_EXCEEDED', 'Vaqt Limitidan Oshdi'), ('ERROR', 'Xatolik')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan Vaqt')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Ishlash Vaqti (sekund)')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.contest', verbose_name='Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.problem', verbose_name='Masala')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuborilgan Kod',
                'verbose_name_plural': 'Yuborilgan Kodlar',
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, verbose_name='Umumiy Ball')),
                ('problems_solved', models.IntegerField(default=0, verbose_name='Yechilgan Masalalar Soni')),
                ('last_submission', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi Yuborish')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi Faollik')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contest.contest', verbose_name='Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Contest Ishtirokchisi',
                'verbose_name_plural': 'Contest Ishtirokchilari',
                'unique_together': {('contest', 'user')},
            },
        ),
    ]
