server {
    listen 7000;
    server_name 194.163.171.25;

    # Maksimal so‘rov hajmi
    client_max_body_size 900M;

    # Statik fayllar
    location /static/ {
        alias /app/staticfiles/;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Media fayllar
    location /media/ {
        alias /app/media/;
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }

    # API so‘rovlarini DRF’ga yo‘naltirish
    location / {
        proxy_pass http://bekendchi-app:8005;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}