# HTTP dan HTTPS ga yo‘naltirish
server {
    listen 80;
    server_name bekendchi.uz www.bekendchi.uz;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name bekendchi.uz www.bekendchi.uz;

    # SSL sertifikat fayllari
    ssl_certificate /etc/letsencrypt/live/bekendchi.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bekendchi.uz/privkey.pem;

    # Maksimal so‘rov hajmi
    client_max_body_size 900M;

    # Statik fayllar
    location /static/ {
        alias /app/staticfiles/;
    }

    # Media fayllar
    location /media/ {
        alias /app/media/;
    }

    # API so‘rovlarini DRF’ga yo‘naltirish
    location / {
        proxy_pass http://app:8005;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}