# Generated by Django 5.2 on 2025-04-16 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ustoz.group')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(choices=[(1, '1-dars'), (2, '2-dars'), (3, '3-dars'), (4, '4-dars'), (5, '5-dars'), (6, '6-dars'), (7, '7-dars'), (8, '8-dars'), (9, '9-dars'), (10, '10-dars'), (11, '11-dars'), (12, '12-dars')])),
                ('is_present', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='ustoz.student')),
            ],
            options={
                'unique_together': {('student', 'lesson_number')},
            },
        ),
    ]
