# Generated by Django 5.2 on 2025-06-16 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ustoz', '0002_alter_attendance_unique_together_student_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidtermAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_number', models.IntegerField(choices=[(1, '1-nazorat'), (2, '2-nazorat'), (3, '3-nazorat'), (4, '4-nazorat'), (5, '5-nazorat'), (6, '6-nazorat')], help_text='Nazorat ishi raqami')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, help_text="Nazorat ishi bo'yicha umumiy izoh", max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_assessments', to='ustoz.student')),
            ],
            options={
                'ordering': ['date', 'assessment_number'],
                'unique_together': {('student', 'assessment_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MidtermTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(help_text='Vazifa turi (masalan, Test, Word amaliyoti, Excel amaliyoti)', max_length=100)),
                ('max_score', models.FloatField(help_text='Vazifa uchun maksimal ball', validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.FloatField(help_text='Talaba olgan ball', validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(blank=True, help_text="Vazifa bo'yicha izoh", max_length=200)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ustoz.midtermassessment')),
            ],
            options={
                'ordering': ['assessment', 'task_type'],
            },
        ),
    ]
